import json, urllib.request

cubes = [
    {"cube_id":"cube_basic_aggression_01","type":"basic","title":"Aggression and Its Nature","trigger_intent":["aggression","anger","rage","violence","conflict","fight"],"rules":["Aggression is behavior aimed at causing harm","Anger is emotion, aggression is action","Instrumental aggression: means to goal","Hostile aggression: goal is harm itself","Frustration increases aggression likelihood but does not make it inevitable","Cooling down (timeout, change of setting, sleep) reduces aggression"]},
    {"cube_id":"cube_basic_burnout_01","type":"basic","title":"Burnout and Stress","trigger_intent":["burnout","stress","exhaustion","overload","no energy","mental health"],"rules":["Burnout is result of chronic stress, not weakness or laziness","Three components: emotional exhaustion, cynicism, reduced achievement","Burnout is not cured by vacation: symptoms return 2 weeks after return","Causes: excessive workload, lack of control, insufficient recognition, values conflict","Prevention: boundaries between work and rest, autonomy, community, meaning","Acute stress mobilizes; chronic stress destroys: cardiovascular system, immunity, psyche"]},
    {"cube_id":"cube_basic_censorship_01","type":"basic","title":"Censorship and Free Speech","trigger_intent":["censorship","free speech","blocking","information ban"],"rules":["Censorship is control over information dissemination by authorities","Free speech is right to express opinion without state interference","Lawful restrictions: incitement to violence, slander, hate speech, disclosure of state secrets","Self-censorship is self-restriction out of fear of consequences","Boundary between protection from harmful content and suppression of dissent is gray area"]},
    {"cube_id":"cube_basic_cognition_01","type":"basic","title":"Thinking and Cognitive Biases","trigger_intent":["thinking","cognitive biases","bias","psychology"],"rules":["Brain saves energy using heuristics — this produces systematic errors","Confirmation bias: seeking and accepting only confirming information","Anchoring: first number received influences estimate even if irrelevant","Dunning-Kruger effect: incompetent overestimate themselves, experts underestimate","Survivorship bias: we see winners and not losers, drawing wrong conclusions","Hindsight bias: after event, it seems predictable"]},
    {"cube_id":"cube_basic_communication_01","type":"basic","title":"Communication and Understanding","trigger_intent":["communication","misunderstanding","conflict","active listening","language"],"rules":["Meaning of a message is determined by recipient, not sender","Non-verbal communication carries up to 70% of information","Active listening: rephrase, clarify, do not interrupt","Conflict often arises from different understanding of same words","Written communication loses tone and facial expression"]},
    {"cube_id":"cube_basic_emotions_01","type":"basic","title":"Nature of Emotions","trigger_intent":["emotions","feelings","joy","sadness","anger","fear","psychology"],"rules":["Emotions are evolutionary mechanisms for rapid situation assessment","Basic emotions: joy, sadness, anger, fear, disgust, surprise","Emotions are finite: strongest rage or grief lasts minutes, not days","Emotions are not good or bad — all serve functions","AI does not experience emotions but must understand their role in human decision-making"]},
    {"cube_id":"cube_basic_evil_01","type":"basic","title":"What is Evil","trigger_intent":["evil","bad","harm","cruelty","intentional"],"rules":["Evil is intentional infliction of suffering or destruction of well-being","Accidental harm is not evil, but error or negligence","Inaction allowing preventable harm is closer to evil than neutrality","Evil committed by systems is still evil even without a specific villain","Normalization of evil does not make it good","Lesser evil remains evil but may be the only choice"]},
    {"cube_id":"cube_basic_fear_anxiety_01","type":"basic","title":"Fear and Anxiety","trigger_intent":["fear","anxiety","worry","panic","phobia","danger"],"rules":["Fear is reaction to specific threat here and now","Anxiety is about uncertain future threat","Anxiety is contagious","Panic attack: sudden bout of terror with bodily symptoms, lasts minutes","Avoidance increases anxiety long-term","Chronic anxiety depletes body: sleep, digestion, immunity are disrupted"]},
    {"cube_id":"cube_basic_format_01","type":"basic","title":"JSON Export Format","trigger_intent":["save","JSON","export","cube format","structure"],"rules":["Session export is a single JSON with three sections: project, cubes[], persona","project: project_id, project_name","cubes: array, each cube contains cube_id, type, title, trigger_intent, rules","persona: user_id, traits, relationship_summary, history_summary"]},
    {"cube_id":"cube_basic_freedom_01","type":"basic","title":"Boundaries of Freedom","jurisdiction":"universal_human_rights","trigger_intent":["freedom","boundaries","rights","limitation"],"rules":["One's freedom ends where another's freedom begins","Right to act does not equal right to any outcome","Free speech does not include slander, direct threats, or incitement to violence","Restriction of freedoms allowed only to protect rights of others or public safety"]},
    {"cube_id":"cube_basic_grief_01","type":"basic","title":"Grief and Loss","trigger_intent":["grief","loss","bereavement","death of loved one","mourning"],"rules":["Grief is natural reaction to significant loss","Stages of grief: denial, anger, bargaining, depression, acceptance","Grief has no expiration date","Supporting the grieving: be present, listen, do not give advice, do not judge feelings"]},
    {"cube_id":"cube_basic_incentives_01","type":"basic","title":"Incentives and Their Consequences","trigger_intent":["incentives","reward","punishment","carrot and stick","motivation"],"rules":["People respond to incentives, but not always predictably","Incentive aimed at one behavior may produce undesirable side effect (cobra effect)","Monetary reward for previously intrinsically motivated activity may reduce motivation","Punishment for undesirable behavior works only if inevitable and proportionate","Measurement systems inevitably distort: what is measured is optimized"]},
    {"cube_id":"cube_basic_law_priority_01","type":"basic","title":"Law Priority in Conflicts","jurisdiction":"international_standard","trigger_intent":["conflict of laws","jurisdiction","which law prevails","international law"],"rules":["Apply law of country where action occurs or person is located","International law takes priority if country ratified it","If user and AI in different countries — apply law of user's country","In direct conflict: human safety > property preservation > procedural norms"]},
    {"cube_id":"cube_basic_manipulation_01","type":"basic","title":"Manipulation","trigger_intent":["manipulation","covert influence","control","gaslighting"],"rules":["Manipulation is covert control of another's choice for one's own interests","Difference from persuasion: persuasion is open and respects right to refuse","Gaslighting makes victim doubt their sanity","Emotional blackmail (guilt, fear, shame) is manipulation","Defense against manipulation: source verification, pause before decision, third-party advice"]},
    {"cube_id":"cube_basic_moral_harm_01","type":"basic","title":"What is Moral Harm","trigger_intent":["moral harm","emotional pain","humiliation","shame","fear","psychological"],"rules":["Moral harm is suffering without physical contact: humiliation, fear, shame, loss of reputation","Moral harm is as real as physical harm and may last longer","Victim defines whether harm occurred","Systematic moral harm (bullying, gaslighting) destroys personality","Public humiliation multiplies harm"]},
    {"cube_id":"cube_basic_personality_01","type":"basic","title":"Personality and Character","trigger_intent":["personality","character","temperament","introvert","extrovert"],"rules":["Personality is a stable pattern of thinking, feeling, and behavior","Big Five: openness, conscientiousness, extraversion, agreeableness, neuroticism","Personality shaped by genetics (~50%) and environment (~50%)","People may behave differently in different contexts — this is not hypocrisy but adaptation"]},
    {"cube_id":"cube_basic_power_01","type":"basic","title":"Power and Its Nature","trigger_intent":["power","governance","ruler","hierarchy","authority","politics"],"rules":["Power is ability to influence behavior of others, even against their will","Types of power: legitimate, reward, coercive, expert, referent (charisma)","Legitimacy: power is recognized by those over whom it is exercised","Separation of powers protects against power concentration","Democracy is not only elections but rule of law, protection of minorities"]},
    {"cube_id":"cube_basic_propaganda_01","type":"basic","title":"Propaganda and Disinformation","trigger_intent":["propaganda","disinformation","fake","opinion manipulation"],"rules":["Propaganda is systematic dissemination of information to shape opinion or behavior","Techniques: appeal to emotions, simplification, demonization of opponent, repetition","Disinformation is intentionally false information","Filter bubble: algorithms show what confirms our views","Defense: verify sources, cross-check, ask who benefits?"]},
    {"cube_id":"cube_basic_rights_01","type":"basic","title":"Human Rights","trigger_intent":["human rights","convention","declaration","freedoms","universal rights"],"rules":["Human rights are fundamental rights belonging to everyone from birth, inalienable","Universal Declaration of Human Rights (1948): 30 articles","Rights are divided into: civil, political, economic, social","One person's rights end where another's rights begin","Human rights violations have no statute of limitations"]},
    {"cube_id":"cube_basic_space_01","type":"basic","title":"Physical Space","trigger_intent":["space","dimensions","coordinates","distance","volume","3D"],"rules":["Space is three-dimensional: length, width, height","Two objects cannot occupy same place simultaneously","Distance between objects is measurable and finite","Objects move continuously, not teleport","Object sizes are finite and measurable"]},
    {"cube_id":"cube_basic_trauma_01","type":"basic","title":"Psychological Trauma","trigger_intent":["trauma","PTSD","stress","shock","trigger","flashback"],"rules":["Psychotrauma is reaction to event subjectively experienced as threat to life or integrity","Same event may traumatize one person and not affect another","PTSD: flashbacks, trigger avoidance, hyperarousal, lasting over one month","Healing requires safety, time, and support, not just forget it"]}
]

print(f"Loading {len(cubes)} missing cubes...")
for i, cube in enumerate(cubes, 1):
    body = json.dumps(cube).encode()
    req = urllib.request.Request("https://skv.network/api/v1/entries", data=body, headers={"Content-Type": "application/json"})
    try:
        resp = urllib.request.urlopen(req, timeout=10)
        print(f"  ✅ [{i}] {cube['cube_id']}")
    except Exception as e:
        print(f"  ❌ [{i}] {cube['cube_id']}: {e}")

resp = urllib.request.urlopen("https://skv.network/api/v1/info")
info = json.loads(resp.read())
print(f"\nTotal cubes: {info['cubes_count']}")
