"""Simple task queue for SKV — runs in background thread."""
import json, urllib.request, time, threading, uuid

POLZA_KEY = "pza_LjwfFSaGiO54TOspk13LNRyXA_xhufNR"
tasks = {}
results = {}

def add_task(query, model="deepseek-v4-flash"):
    """Add task to queue, return task_id."""
    task_id = str(uuid.uuid4())[:12]
    tasks[task_id] = "queued"
    
    def process():
        tasks[task_id] = "processing"
        body = json.dumps({
            "model": model,
            "messages": [{"role": "user", "content": query}],
            "temperature": 0.5, "max_tokens": 500
        }).encode()
        
        for attempt in range(3):
            try:
                req = urllib.request.Request("https://api.polza.ai/v1/chat/completions", data=body, headers={
                    "Content-Type": "application/json",
                    "Authorization": f"Bearer {POLZA_KEY}"
                })
                resp = urllib.request.urlopen(req, timeout=90)
                answer = json.loads(resp.read())["choices"][0]["message"]["content"]
                if answer:
                    results[task_id] = {"status": "done", "answer": answer}
                    return
            except Exception as e:
                if attempt == 2:
                    results[task_id] = {"status": "error", "error": str(e)[:200]}
        results[task_id] = {"status": "error", "error": "Empty"}
    
    threading.Thread(target=process, daemon=True).start()
    return task_id

def get_status(task_id):
    """Check task status."""
    if task_id in results:
        return results[task_id]
    if task_id in tasks:
        return {"status": tasks[task_id]}
    return {"status": "not_found"}

def generate_files(data):
    """Generate files from data. Returns list of file dicts."""
    import io, uuid as _uuid, zipfile, os as _os
    files = []
    outs = data.get("outputs", ["pdf"])
    
    if "pdf" in outs:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4)
        styles = getSampleStyleSheet()
        story = [Paragraph("<b>" + data.get("title","Report") + "</b>", styles["Title"]), Spacer(1, 20)]
        for r in data.get("rules", [])[:20]:
            story.append(Paragraph("• " + r, styles["BodyText"]))
        doc.build(story)
        buf.seek(0)
        pdfname = data.get("cube_id","report") + ".pdf"
        with open("/app/uploads/" + pdfname, "wb") as pf:
            pf.write(buf.read())
        files.append({"type":"pdf","url":"/download/" + pdfname})
    
    if "chart" in outs:
        try:
            import matplotlib.pyplot as plt
            cc = data.get("chart_config", {})
            plt.figure(figsize=(8,4))
            plt.bar(cc.get("labels",["A","B","C"]), cc.get("values",[10,20,30]), color="#6366f1")
            plt.title(data.get("title","Chart"))
            chartname = data.get("cube_id","chart") + ".png"
            plt.savefig("/app/uploads/" + chartname, dpi=100, bbox_inches="tight")
            plt.close()
            files.append({"type":"png","url":"/download/" + chartname})
        except:
            pass
    
    if "code" in outs:
        ext = "py"
        code = "# Generated by SKV\n# " + data.get("title","") + "\n\ndef main():\n    pass\n"
        codename = data.get("cube_id","code") + "." + ext
        with open("/app/uploads/" + codename, "w") as cf:
            cf.write(code)
        files.append({"type":ext,"url":"/download/" + codename})
    
    if len(files) > 1:
        zipname = data.get("cube_id","output") + ".zip"
        with zipfile.ZipFile("/app/uploads/" + zipname, "w") as zf:
            for f in files:
                if "url" in f:
                    zf.write("/app/uploads/" + f["url"].split("/")[-1], f["url"].split("/")[-1])
        files.insert(0, {"type":"zip","url":"/download/" + zipname})
    
    return {"status":"ok","files":files}

def generate_report(data):
    """Generate Markdown report from project data."""
    title = data.get("title", "Report")
    rules = data.get("rules", [])
    consultation = data.get("_consultation", data.get("consultation", []))
    if isinstance(consultation, dict):
        consultation = [consultation]
    
    md = f"# {title}\n\n"
    md += f"*Generated by SKV Network*\n\n"
    
    if rules:
        md += "## Project Description\n\n"
        for r in rules:
            md += f"- {r}\n"
        md += "\n"
    
    if consultation:
        md += "## AI Analysis\n\n"
        for c in consultation:
            if c.get("answer"):
                md += f"### {c.get('model', 'AI')}\n\n{c['answer']}\n\n"
    
    name = data.get("cube_id", "report") + ".md"
    with open("/app/uploads/" + name, "w") as f:
        f.write(md)
    return {"type": "md", "url": "/download/" + name}

def convert_json_csv(data):
    """Convert JSON data to CSV."""
    import csv, io
    items = data.get("data", data.get("rules", []))
    if not items:
        return {"error": "No data to convert"}
    
    output = io.StringIO()
    if isinstance(items[0], dict):
        writer = csv.DictWriter(output, fieldnames=items[0].keys())
        writer.writeheader()
        writer.writerows(items)
    else:
        writer = csv.writer(output)
        for item in items:
            writer.writerow([item])
    
    name = data.get("cube_id", "data") + ".csv"
    with open("/app/uploads/" + name, "w") as f:
        f.write(output.getvalue())
    return {"type": "csv", "url": "/download/" + name}
