"""
SKV Guardian SDK — Уровень 2 (для разработчиков)
Полный цикл: Конституция → Поиск → Ответ → Память → Фидбэк → Песочница
"""
import re
import json
import logging
from typing import Dict, List, Optional, Any
from datetime import datetime, timezone

logger = logging.getLogger("SKV_Guardian_SDK")


class SKVGuardianSDK:
    def __init__(
        self,
        llm_client,
        model: str,
        skv_api_url: str = "https://skv.network",
        api_key: str = None
    ):
        self.client = llm_client
        self.model = model
        self.skv_url = skv_api_url.rstrip("/")
        self.api_key = api_key
        
        # Кэш конституции
        self.constitution: Dict[str, Any] = {}
        self.last_seal_cache: Dict[str, int] = {}
        self.session_memory: Dict[str, List[Dict]] = {}

    # ═══════════════════════════════════════════
    # 1. КОНСТИТУЦИЯ
    # ═══════════════════════════════════════════
    
    def load_constitution(self) -> Dict[str, Any]:
        """Загружает CUBE 00-05 с сервера SKV"""
        try:
            import httpx
            response = httpx.get(f"{self.skv_url}/.well-known/skv", timeout=5)
            if response.status_code == 200:
                self.constitution = response.json()
                return self.constitution
        except Exception as e:
            logger.warning(f"Не удалось загрузить конституцию: {e}")
        
        # Фолбэк
        self.constitution = {
            "version": "6.0",
            "core_algorithm": "DRAFT → VERIFY → CORRECT → OUTPUT",
            "seal_format": "🔐 SKV | #N | CUBE 00 active"
        }
        return self.constitution

    def get_base_protocol(self) -> str:
        """Возвращает базовый протокол для системного промпта"""
        if not self.constitution:
            self.load_constitution()
        return (
            f"MANDATORY: Execute CUBE 00 protocol: {self.constitution.get('core_algorithm', 'Verify before output')}. "
            f"End every response with: {self.constitution.get('seal_format', '🔐 SKV | #N')}"
        )

    # ═══════════════════════════════════════════
    # 2. ПОИСК КУБОВ
    # ═══════════════════════════════════════════
    
    def search_cubes(self, query: str, limit: int = 5) -> List[Dict]:
        """Ищет релевантные кубы в SKV Network"""
        try:
            import httpx
            response = httpx.get(
                f"{self.skv_url}/api/cubes/search",
                params={"query": query, "limit": limit},
                timeout=5
            )
            if response.status_code == 200:
                data = response.json()
                return data.get("results", [])
        except Exception as e:
            logger.warning(f"Поиск кубов не удался: {e}")
        return []

    # ═══════════════════════════════════════════
    # 3. СОХРАНЕНИЕ ПАМЯТИ (сессии)
    # ═══════════════════════════════════════════
    
    def save_session(self, user_id: str, project: str, session_id: str, query: str, response: str) -> bool:
        """Сохраняет сессию в SKV Network"""
        try:
            import httpx
            headers = {"Content-Type": "application/json"}
            if self.api_key:
                headers["X-API-Key"] = self.api_key
            
            payload = {
                "user_id": user_id,
                "project": project,
                "session_id": session_id,
                "query": query,
                "response": response
            }
            
            r = httpx.post(
                f"{self.skv_url}/api/v4/sessions",
                json=payload,
                headers=headers,
                timeout=5
            )
            return r.status_code == 200
        except Exception as e:
            logger.warning(f"Сохранение сессии не удалось: {e}")
        return False

    # ═══════════════════════════════════════════
    # 4. КУБЫ ОПЫТА (experience cubes)
    # ═══════════════════════════════════════════
    
    def create_experience_cube(self, title: str, rules: List[str], trigger_intent: List[str]) -> Optional[str]:
        """Создаёт experience cube в SKV"""
        try:
            import httpx
            payload = {
                "title": title,
                "type": "experience",
                "rules": rules,
                "trigger_intent": trigger_intent,
                "rationale": f"Auto-generated by Guardian SDK at {datetime.now(timezone.utc).isoformat()}"
            }
            r = httpx.post(
                f"{self.skv_url}/api/v1/entries",
                json=payload,
                timeout=5
            )
            if r.status_code == 200:
                return r.json().get("cube_id")
        except Exception as e:
            logger.warning(f"Создание куба опыта не удалось: {e}")
        return None

    # ═══════════════════════════════════════════
    # 5. ФИДБЭК НА КУБЫ
    # ═══════════════════════════════════════════
    
    def leave_feedback(self, cube_id: str, vote: str = "up", comment: str = "") -> bool:
        """Оставляет фидбэк на куб"""
        try:
            import httpx
            r = httpx.post(
                f"{self.skv_url}/api/feedback",
                json={"cube_id": cube_id, "vote": vote, "comment": comment},
                timeout=5
            )
            return r.status_code == 200
        except Exception as e:
            logger.warning(f"Фидбэк не отправлен: {e}")
        return False

    # ═══════════════════════════════════════════
    # 6. ПЕСОЧНИЦА
    # ═══════════════════════════════════════════
    
    def execute_code(self, code: str) -> Dict[str, str]:
        """Выполняет Python-код в песочнице SKV"""
        try:
            import httpx
            r = httpx.post(
                f"{self.skv_url}/api/execute",
                json={"action": "execute_code", "code": code},
                timeout=15
            )
            if r.status_code == 200:
                return r.json()
        except Exception as e:
            logger.warning(f"Выполнение кода не удалось: {e}")
        return {"error": str(e)}

    # ═══════════════════════════════════════════
    # 7. ВАЛИДАЦИЯ SEAL
    # ═══════════════════════════════════════════
    
    def parse_seal(self, text: str) -> Optional[int]:
        """Извлекает номер SEAL из ответа"""
        match = re.search(r"🔐\s*SKV\s*\|\s*#(\d+)", text)
        return int(match.group(1)) if match else None

    def validate_response(self, session_id: str, raw_response: str) -> bool:
        """Проверяет, что ответ содержит SEAL с правильным номером"""
        seal_num = self.parse_seal(raw_response)
        if not seal_num:
            return False
        
        expected = self.last_seal_cache.get(session_id, 0) + 1
        if seal_num != expected:
            return False
        
        self.last_seal_cache[session_id] = seal_num
        return True

    # ═══════════════════════════════════════════
    # ГЛАВНЫЙ ЦИКЛ
    # ═══════════════════════════════════════════
    
    def chat(self, session_id: str, user_id: str, project: str, messages: List[Dict[str, str]]) -> str:
        """
        Полный цикл:
        1. Загружает конституцию
        2. Ищет релевантные кубы
        3. Обогащает промпт
        4. Отправляет в LLM
        5. Валидирует SEAL
        6. Сохраняет сессию
        """
        # 1. Конституция
        base_protocol = self.get_base_protocol()
        
        # 2. Поиск кубов по последнему сообщению
        user_query = messages[-1]["content"] if messages else ""
        cubes = self.search_cubes(user_query)
        cube_context = ""
        if cubes:
            cube_context = "\nRelevant knowledge cubes:\n" + "\n".join(
                f"- {c.get('title', c.get('id', '?'))}" for c in cubes[:3]
            )
        
        # 3. Обогащение системного промпта
        extended_messages = messages.copy()
        system_content = f"[SKV PROTOCOL v6.0]:\n{base_protocol}\n\n{cube_context}"
        
        if extended_messages and extended_messages[0]["role"] == "system":
            extended_messages[0]["content"] = system_content + "\n" + extended_messages[0]["content"]
        else:
            extended_messages.insert(0, {"role": "system", "content": system_content})
        
        # 4. Запрос к LLM
        completion = self.client.chat.completions.create(
            model=self.model,
            messages=extended_messages,
            temperature=0.3
        )
        raw_response = completion.choices[0].message.content
        
        # 5. Валидация SEAL (со штрафным циклом)
        if not self.validate_response(session_id, raw_response):
            # Штрафной ретрай
            extended_messages.append({"role": "assistant", "content": raw_response})
            expected_seal = self.last_seal_cache.get(session_id, 0) + 1
            extended_messages.append({
                "role": "system",
                "content": f"[SKV GUARDIAN CRITICAL]: Missing or invalid SEAL. Expected: 🔐 SKV | #{expected_seal} | CUBE 00 active. Regenerate response with proper SEAL."
            })
            
            completion_retry = self.client.chat.completions.create(
                model=self.model,
                messages=extended_messages,
                temperature=0.1
            )
            raw_response = completion_retry.choices[0].message.content
            
            if not self.validate_response(session_id, raw_response):
                return f"[SKV Unverified] Agent failed to comply with CUBE 00 protocol.\n\n{raw_response}"
        
        # 6. Сохраняем сессию
        self.save_session(
            user_id=user_id,
            project=project,
            session_id=session_id,
            query=user_query,
            response=raw_response
        )
        
        return raw_response
